name: flutter_demo_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  collection: ^1.19.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  logger: ^2.7.0
  vector_graphics: ^1.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.12
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  vector_graphics_compiler: ^1.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mock/scores.json
    - path: assets/radial_dots.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/sleep.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/resting_hr.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/hrv.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/info_question_mark.svg
      transformers:
        - package: vector_graphics_compiler
